#!/bin/bash
# changeBrightness

# Arbitrary but unique message id
msgId="991050"

#change the brightness using xbacklight
#	-inc <increase>			increases brightness
#	-dec <decrease>			decreases brightness
xbacklight -time 1 -steps 1 $@

# Query amixer for the current volume and whether or not the speaker is muted
brightness="$(printf "%0.0f" $(xbacklight -get))"

# Show the brightness notification
dunstify -a "changeBrightness" -u low -i display-brightness -r "$msgId" \
"Brightness: ${brightness}%" 

# Play the volume changed sound
canberra-gtk-play -i audio-volume-change -d "changeBrightness"
